# Generated by Django 5.0.6 on 2026-09-13 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('service_needed', models.CharField(blank=True, max_length=150)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_handled', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClinicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_name', models.CharField(default='Genet Dental Specialized Center', max_length=200)),
                ('tagline', models.CharField(default='Smiles Always...', max_length=200)),
                ('established_year', models.PositiveIntegerField(default=2014)),
                ('hero_heading', models.CharField(default='Smiles Always...', max_length=200)),
                ('hero_paragraph', models.TextField(default='Experience world-class dental care in a state-of-the-art facility. We combine rigorous clinical standards with boutique hospitality for a truly premium patient journey.')),
                ('years_experience', models.PositiveIntegerField(default=12)),
                ('patients_count_label', models.CharField(default='23k+', max_length=20)),
                ('excellence_heading', models.CharField(default='Excellence in Dental Care', max_length=200)),
                ('excellence_paragraph', models.TextField(default='At Genet Specialized Dental Center, we are dedicated to providing personalized, high-quality dental care in a comfortable and stress-free environment. Our team of experienced specialists uses the latest technology to ensure optimal oral health for you and your family.')),
                ('address_line', models.CharField(default='Junaibi Tower, 2nd Floor, Muroor Road', max_length=255)),
                ('address_city', models.CharField(default='Abu Dhabi, UAE', max_length=100)),
                ('phone', models.CharField(default='02 666 99 45', max_length=50)),
                ('whatsapp', models.CharField(default='050 346 9945', max_length=50)),
                ('email', models.EmailField(default='info@genetdental.com', max_length=254)),
                ('working_hours', models.CharField(default='Sun - Sat, 9:30 AM - 8:30 PM', max_length=100)),
                ('map_image', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('hero_photo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('smiles_wordmark', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('quick_services_row', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('insurance_strip', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('excellence_video', models.FileField(blank=True, null=True, upload_to='branding/')),
            ],
            options={
                'verbose_name': 'Clinic Info',
                'verbose_name_plural': 'Clinic Info',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('specialty', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='doctors/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(upload_to='icons/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=150)),
                ('role_label', models.CharField(default='Verified Patient', max_length=100)),
                ('quote', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(upload_to='treatments/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
