# Generated by Django 5.0.6 on 2026-09-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_repair_doctor_schema'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treatment',
            options={},
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='photo',
        ),
        migrations.AddField(
            model_name='treatment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='treatments/'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
    ]
