# Generated by Django 5.0.6 on 2026-09-21 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_alter_treatment_options_remove_treatment_photo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='icon',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='service',
            name='slug',
        ),
    ]
