# Generated by Django 5.0.6 on 2026-09-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_rename_icon_service_image_remove_service_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='services/icons/'),
        ),
    ]
